const Bag = require("./Bags")
const Passenger = require("./Passenger")
const CrewMember = require("./CrewMember")
const Plane = require("./Plane")
const Airport = require("./Airport")

const bag1 = new Bag(8)
const bag2 = new Bag(2)
const bag3 = new Bag(20)
const bag4 = new Bag(27)
const bag5 = new Bag(14)

const passenger1 = new Passenger("John Doe", 1234, 43)
passenger1.addBag(bag1)
passenger1.addBag(bag3)
const passenger2 = new Passenger("Mary Foo", 3241, 44)
passenger2.addBag(bag2)
passenger2.addBag(bag4)
const crewMember1 = new CrewMember("Captain John", "Captain", 4001)
crewMember1.addBag(bag5)
const plane1 = new Plane("474")
plane1.board(passenger1)
plane1.board(passenger2)
plane1.boardCrew(crewMember1)
const airport1 = new Airport("Heathrow")
airport1.arrivals(plane1)

console.log(airport1)