const Bag = require("./Bags")
const Passenger = require("./Passenger")
const CrewMember = require("./CrewMember")
const Plane = require("./Plane")
const Airport = require("./Airport")

const bag1 = new Bag(8)
const bag2 = new Bag(2)
const bag3 = new Bag(20)
const bag4 = new Bag(27)
const bag5 = new Bag(14)
const bag6 = new Bag(6)
const bag7 = new Bag(8)
const bag8 = new Bag(23)
const bag9 = new Bag(37)
const bag10 = new Bag(24)

const passenger1 = new Passenger("John Doe", 1234, 43)
passenger1.addBag(bag1)
passenger1.addBag(bag3)
const passenger2 = new Passenger("Mary Foo", 3241, 44)
passenger2.addBag(bag2)
passenger2.addBag(bag4)
const passenger3 = new Passenger("Jane Bool", 3643, 32)
passenger2.addBag(bag6)
const passenger4 = new Passenger("Mark Taylor", 7684, 12)
passenger2.addBag(bag7)
const passenger5 = new Passenger("Sean Tyler", 0852, 14)
passenger2.addBag(bag8)
const crewMember1 = new CrewMember("Captain John Scott", "Captain", 4001)
crewMember1.addBag(bag5)
const crewMember2 = new CrewMember("Captain Clair Jones", "Captain", 5667)
crewMember1.addBag(bag9)
const crewMember3 = new CrewMember("Julien Major", "Stuard", 6786)
crewMember1.addBag(bag10)
const plane1 = new Plane("474")
plane1.board(passenger1)
plane1.board(passenger2)
plane1.board(crewMember1)
const plane2 = new Plane("Speed747")
plane2.board(passenger3)
plane2.board(passenger4)
plane2.board(passenger5)
plane2.board(crewMember2)
plane2.board(crewMember3)
const airport1 = new Airport("Heathrow")
const airport2 = new Airport("Gatwick")

console.log(plane1.currentCapacity[0].bags)